// <auto-generated />
namespace Ticketing.Persistence.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Chanage_UserIdFk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chanage_UserIdFk));
        
        string IMigrationMetadata.Id
        {
            get { return "201708271250173_Chanage_UserIdFk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
